/**
 * Principais cidades atendidas por cada DDD. A lista não é exaustiva: cada
 * código cobre dezenas de municípios. Estão aqui as maiores e mais buscadas.
 */
export const cities = {
  11: [
    "São Paulo",
    "Guarulhos",
    "Osasco",
    "Santo André",
    "São Bernardo do Campo",
    "Mogi das Cruzes",
    "Barueri",
    "Jundiaí",
    "Carapicuíba",
    "Diadema",
  ],
  12: [
    "São José dos Campos",
    "Taubaté",
    "Jacareí",
    "Guaratinguetá",
    "Caraguatatuba",
    "Ubatuba",
    "Pindamonhangaba",
    "Lorena",
  ],
  13: [
    "Santos",
    "São Vicente",
    "Guarujá",
    "Praia Grande",
    "Cubatão",
    "Registro",
    "Itanhaém",
    "Peruíbe",
  ],
  14: ["Bauru", "Marília", "Jaú", "Botucatu", "Avaré", "Lins", "Ourinhos", "Lençóis Paulista"],
  15: ["Sorocaba", "Itapetininga", "Itu", "Tatuí", "Votorantim", "Itapeva", "Salto"],
  16: [
    "Ribeirão Preto",
    "Franca",
    "Araraquara",
    "São Carlos",
    "Sertãozinho",
    "Barretos",
    "Jaboticabal",
    "Batatais",
  ],
  17: [
    "São José do Rio Preto",
    "Catanduva",
    "Votuporanga",
    "Fernandópolis",
    "Mirassol",
    "Jales",
    "Olímpia",
  ],
  18: ["Presidente Prudente", "Araçatuba", "Birigui", "Assis", "Dracena", "Tupã", "Andradina"],
  19: [
    "Campinas",
    "Piracicaba",
    "Limeira",
    "Americana",
    "Sumaré",
    "Rio Claro",
    "Indaiatuba",
    "Hortolândia",
    "Paulínia",
  ],
  21: [
    "Rio de Janeiro",
    "Niterói",
    "Duque de Caxias",
    "Nova Iguaçu",
    "São Gonçalo",
    "Belford Roxo",
    "São João de Meriti",
    "Magé",
    "Itaboraí",
    "Maricá",
  ],
  22: [
    "Campos dos Goytacazes",
    "Macaé",
    "Cabo Frio",
    "Nova Friburgo",
    "Rio das Ostras",
    "Armação dos Búzios",
    "Itaperuna",
    "Araruama",
  ],
  24: [
    "Volta Redonda",
    "Petrópolis",
    "Barra Mansa",
    "Resende",
    "Angra dos Reis",
    "Teresópolis",
    "Três Rios",
    "Barra do Piraí",
  ],
  27: [
    "Vitória",
    "Vila Velha",
    "Serra",
    "Cariacica",
    "Guarapari",
    "Linhares",
    "Colatina",
    "São Mateus",
    "Aracruz",
  ],
  28: [
    "Cachoeiro de Itapemirim",
    "Alegre",
    "Castelo",
    "Guaçuí",
    "Itapemirim",
    "Marataízes",
    "Mimoso do Sul",
  ],
  31: [
    "Belo Horizonte",
    "Contagem",
    "Betim",
    "Ribeirão das Neves",
    "Ipatinga",
    "Sete Lagoas",
    "Nova Lima",
    "Itabira",
    "Ouro Preto",
  ],
  32: [
    "Juiz de Fora",
    "Barbacena",
    "Muriaé",
    "Ubá",
    "Cataguases",
    "São João del-Rei",
    "Leopoldina",
  ],
  33: ["Governador Valadares", "Teófilo Otoni", "Caratinga", "Manhuaçu", "Almenara", "Nanuque"],
  34: ["Uberlândia", "Uberaba", "Araguari", "Patos de Minas", "Ituiutaba", "Araxá", "Patrocínio"],
  35: [
    "Poços de Caldas",
    "Pouso Alegre",
    "Varginha",
    "Itajubá",
    "Passos",
    "Alfenas",
    "Lavras",
    "Três Corações",
  ],
  37: [
    "Divinópolis",
    "Itaúna",
    "Formiga",
    "Pará de Minas",
    "Bom Despacho",
    "Oliveira",
    "Nova Serrana",
  ],
  38: ["Montes Claros", "Diamantina", "Pirapora", "Janaúba", "Januária", "Unaí", "Paracatu"],
  41: [
    "Curitiba",
    "São José dos Pinhais",
    "Colombo",
    "Pinhais",
    "Araucária",
    "Paranaguá",
    "Campo Largo",
    "Fazenda Rio Grande",
  ],
  42: ["Ponta Grossa", "Guarapuava", "Castro", "Irati", "Telêmaco Borba", "União da Vitória"],
  43: [
    "Londrina",
    "Apucarana",
    "Arapongas",
    "Cambé",
    "Rolândia",
    "Cornélio Procópio",
    "Jacarezinho",
  ],
  44: ["Maringá", "Umuarama", "Campo Mourão", "Paranavaí", "Cianorte", "Sarandi"],
  45: ["Cascavel", "Foz do Iguaçu", "Toledo", "Medianeira", "Marechal Cândido Rondon"],
  46: ["Francisco Beltrão", "Pato Branco", "Dois Vizinhos", "Palmas"],
  47: [
    "Joinville",
    "Blumenau",
    "Itajaí",
    "Balneário Camboriú",
    "Jaraguá do Sul",
    "Brusque",
    "São Bento do Sul",
    "Rio do Sul",
  ],
  48: [
    "Florianópolis",
    "São José",
    "Palhoça",
    "Criciúma",
    "Tubarão",
    "Laguna",
    "Araranguá",
    "Biguaçu",
  ],
  49: ["Chapecó", "Lages", "Caçador", "Joaçaba", "Concórdia", "Xanxerê", "Videira"],
  51: [
    "Porto Alegre",
    "Canoas",
    "Gravataí",
    "Novo Hamburgo",
    "São Leopoldo",
    "Viamão",
    "Alvorada",
    "Guaíba",
  ],
  53: ["Pelotas", "Rio Grande", "Bagé", "Santa Vitória do Palmar", "Jaguarão", "Camaquã"],
  54: [
    "Caxias do Sul",
    "Passo Fundo",
    "Bento Gonçalves",
    "Erechim",
    "Farroupilha",
    "Vacaria",
    "Gramado",
    "Canela",
  ],
  55: [
    "Santa Maria",
    "Uruguaiana",
    "Santana do Livramento",
    "Santo Ângelo",
    "Ijuí",
    "Cruz Alta",
    "Alegrete",
    "São Borja",
  ],
  61: [
    "Brasília",
    "Taguatinga",
    "Ceilândia",
    "Gama",
    "Sobradinho",
    "Planaltina",
    "Águas Lindas de Goiás",
    "Valparaíso de Goiás",
    "Luziânia",
    "Formosa",
  ],
  62: [
    "Goiânia",
    "Aparecida de Goiânia",
    "Anápolis",
    "Trindade",
    "Senador Canedo",
    "Goianésia",
    "Inhumas",
  ],
  63: [
    "Palmas",
    "Araguaína",
    "Gurupi",
    "Porto Nacional",
    "Paraíso do Tocantins",
    "Colinas do Tocantins",
  ],
  64: ["Rio Verde", "Itumbiara", "Jataí", "Caldas Novas", "Catalão", "Mineiros", "Quirinópolis"],
  65: ["Cuiabá", "Várzea Grande", "Cáceres", "Tangará da Serra", "Diamantino", "Poconé"],
  66: [
    "Rondonópolis",
    "Sinop",
    "Sorriso",
    "Barra do Garças",
    "Lucas do Rio Verde",
    "Alta Floresta",
    "Primavera do Leste",
  ],
  67: [
    "Campo Grande",
    "Dourados",
    "Três Lagoas",
    "Corumbá",
    "Ponta Porã",
    "Naviraí",
    "Nova Andradina",
  ],
  68: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó"],
  69: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal", "Rolim de Moura", "Jaru"],
  71: [
    "Salvador",
    "Lauro de Freitas",
    "Camaçari",
    "Simões Filho",
    "Candeias",
    "Dias d'Ávila",
    "Mata de São João",
  ],
  73: ["Ilhéus", "Itabuna", "Porto Seguro", "Eunápolis", "Teixeira de Freitas", "Jequié"],
  74: ["Juazeiro", "Jacobina", "Senhor do Bonfim", "Irecê", "Campo Formoso", "Xique-Xique"],
  75: [
    "Feira de Santana",
    "Alagoinhas",
    "Santo Antônio de Jesus",
    "Serrinha",
    "Valença",
    "Cruz das Almas",
    "Paulo Afonso",
  ],
  77: [
    "Vitória da Conquista",
    "Barreiras",
    "Guanambi",
    "Brumado",
    "Bom Jesus da Lapa",
    "Luís Eduardo Magalhães",
  ],
  79: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "Estância", "São Cristóvão"],
  81: [
    "Recife",
    "Jaboatão dos Guararapes",
    "Olinda",
    "Paulista",
    "Caruaru",
    "Cabo de Santo Agostinho",
    "Vitória de Santo Antão",
  ],
  82: ["Maceió", "Arapiraca", "Rio Largo", "Palmeira dos Índios", "Penedo", "União dos Palmares"],
  83: ["João Pessoa", "Campina Grande", "Santa Rita", "Bayeux", "Patos", "Sousa", "Cajazeiras"],
  84: ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Caicó", "Macaíba"],
  85: ["Fortaleza", "Caucaia", "Maracanaú", "Eusébio", "Aquiraz", "Pacajus", "Horizonte"],
  86: ["Teresina", "Parnaíba", "Piripiri", "Campo Maior", "Barras", "Altos"],
  87: ["Petrolina", "Garanhuns", "Serra Talhada", "Arcoverde", "Salgueiro", "Belo Jardim"],
  88: ["Juazeiro do Norte", "Sobral", "Crato", "Iguatu", "Quixadá", "Crateús", "Itapipoca"],
  89: ["Picos", "Floriano", "Oeiras", "São Raimundo Nonato", "Bom Jesus", "Corrente"],
  91: ["Belém", "Ananindeua", "Marituba", "Castanhal", "Abaetetuba", "Bragança", "Capanema"],
  92: ["Manaus", "Itacoatiara", "Manacapuru", "Parintins", "Iranduba", "Presidente Figueiredo"],
  93: ["Santarém", "Altamira", "Itaituba", "Oriximiná", "Monte Alegre", "Óbidos"],
  94: ["Marabá", "Parauapebas", "Redenção", "Tucuruí", "Canaã dos Carajás", "Xinguara"],
  95: ["Boa Vista", "Rorainópolis", "Caracaraí", "Pacaraima", "Alto Alegre"],
  96: ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Mazagão"],
  97: ["Tefé", "Coari", "Tabatinga", "Humaitá", "Lábrea", "Benjamin Constant"],
  98: ["São Luís", "São José de Ribamar", "Paço do Lumiar", "Pinheiro", "Chapadinha", "Santa Inês"],
  99: ["Imperatriz", "Caxias", "Timon", "Codó", "Açailândia", "Bacabal", "Balsas"],
};

export const citiesForDdd = ddd => cities[ddd] ?? [];
